last_change = 2024-07-14T14:57:12.911625Z
addr = 0x20ee84
size = 0x28
name = "RtlWriteTryAcquireTickLock"
type = "char"

[header]
last_change = 2024-07-14T14:57:12.911625Z
name = "RtlWriteTryAcquireTickLock"
addr = 0x20ee84
type = "char"

[header.args.0x0]
offset = 0x0
name = "UpdateLock"
type = "_KUSER_SHARED_DATA *"
size = 0x8
