last_change = 2024-07-14T14:49:42.446041Z
name = "$1202F1CE9F61399A177A72C831B7F70E"
size = 0x8

[members.0x0]
name = "AllocateEx"
offset = 0x0
type = "void *(__fastcall *)(_POOL_TYPE, unsigned long long, unsigned int, _LOOKASIDE_LIST_EX *)"
size = 0x8

[members.0x1]
name = "Allocate"
offset = 0x1
type = "void *(__fastcall *)(_POOL_TYPE, unsigned long long, unsigned int)"
size = 0x8
