last_change = 2024-07-14T14:49:42.446041Z
name = "$1295C7652040702D9335A0311A3EC089"
size = 0x8

[members.0x0]
name = "SnapTimeLast"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x1]
name = "EnergyConsumed"
offset = 0x1
type = "unsigned long long"
size = 0x8
