last_change = 2024-07-14T14:49:42.446041Z
name = "$1478958CD18659349EECCFF09CEBE206"
size = 0x8

[members.0x0]
name = "UserApcRoutine"
offset = 0x0
type = "void (__fastcall *)(void *, _IO_STATUS_BLOCK *, unsigned int)"
size = 0x8

[members.0x1]
name = "IssuingProcess"
offset = 0x1
type = "void *"
size = 0x8
