last_change = 2024-07-14T14:49:42.446041Z
name = "$1C522E00CDFB3DDA2387AB30959AD8DB"
size = 0x8

[members.0x0]
name = "IdleTimeExpiration"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x1]
name = "IdleWakeTime"
offset = 0x1
type = "volatile long long"
size = 0x8
