last_change = 2024-07-14T14:49:42.446041Z
name = "$25FDEB30A5BA9A90CC672977E58E42F1"
size = 0xc

[members.0x0]
name = "Start"
offset = 0x0
type = "_LARGE_INTEGER"
size = 0x8

[members.0x8]
name = "Length"
offset = 0x8
type = "unsigned int"
size = 0x4
