last_change = 2024-07-14T14:49:42.446041Z
name = "$2C0B5C34625B6665B95D29438DEE1BAC"
size = 0x8

[members.0x0]
name = "FreeEx"
offset = 0x0
type = "void (__fastcall *)(void *, _LOOKASIDE_LIST_EX *)"
size = 0x8

[members.0x1]
name = "Free"
offset = 0x1
type = "void (__fastcall *)(void *)"
size = 0x8
