last_change = 2024-07-14T14:49:42.446041Z
name = "$437EDEAFE33DAFED4793B8A3A762EFC4"
size = 0x2

[members.0x0]
name = "PairLocalLow"
offset = 0x0
type = "unsigned char"
size = 0x1

[members.0x1]
name = "_bf_1"
offset = 0x1
type = "char"
size = 0x1
