last_change = 2024-07-14T14:49:42.446041Z
name = "$4B94A638C9572C40F7312179A2B431F6"
size = 0x2

[members.0x0]
name = "gap0"
offset = 0x0
type = "_BYTE"
size = 0x1

[members.0x1]
name = "MutantSize"
offset = 0x1
type = "unsigned char"
size = 0x1
