last_change = 2024-07-14T14:49:42.446041Z
name = "$587E166413A0BC9D4B6487D1ABA99C2F"
size = 0x2

[members.0x0]
name = "NmiActive"
offset = 0x0
type = "unsigned char"
size = 0x1

[members.0x1]
name = "MceActive"
offset = 0x1
type = "unsigned char"
size = 0x1
