last_change = 2024-07-14T14:49:42.446041Z
name = "$5C4ADDEA2BFAF8433592EE691D38ECCB"
size = 0x8

[members.0x0]
name = "CurrentStackLocation"
offset = 0x0
type = "_IO_STACK_LOCATION *"
size = 0x8

[members.0x1]
name = "PacketType"
offset = 0x1
type = "unsigned int"
size = 0x4
