last_change = 2024-07-14T14:49:42.446041Z
name = "$65F3014B83CBA7D0B98DA1788953A33A"
size = 0x2

[members.0x0]
name = "PairRemoteLow"
offset = 0x0
type = "unsigned char"
size = 0x1

[members.0x1]
name = "Reserved2"
offset = 0x1
type = "unsigned char"
size = 0x1
