last_change = 2024-07-14T14:49:42.446041Z
name = "$69138CE2BB6A34B6EE0EDED588F41203"
size = 0x10

[members.0x0]
name = "Group"
offset = 0x0
type = "unsigned short"
size = 0x2

[members.0x2]
name = "MessageCount"
offset = 0x2
type = "unsigned short"
size = 0x2

[members.0x4]
name = "Vector"
offset = 0x4
type = "unsigned int"
size = 0x4

[members.0x8]
name = "Affinity"
offset = 0x8
type = "unsigned long long"
size = 0x8
