last_change = 2024-07-14T14:49:42.446041Z
name = "$691F31E4784ED8799E7825D9042CAADE"
size = 0x8

[members.0x0]
name = "UserIosb"
offset = 0x0
type = "_IO_STATUS_BLOCK *"
size = 0x8

[members.0x1]
name = "IoRingContext"
offset = 0x1
type = "void *"
size = 0x8
