last_change = 2024-07-14T14:49:42.446041Z
name = "$6C467299E1DD150E8FDAFB428553E9E9"
size = 0xc

[members.0x0]
name = "Start"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "Length"
offset = 0x4
type = "unsigned int"
size = 0x4

[members.0x8]
name = "Reserved"
offset = 0x8
type = "unsigned int"
size = 0x4
