last_change = 2024-07-14T14:49:42.446041Z
name = "$74A749D08003D8EA6488D13162AFD0DD"
size = 0x18

[members.0x0]
name = "TrappedSecurityDomain"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "BpbState"
offset = 0x8
type = "unsigned short"
size = 0x2

[members.0xa]
name = "BpbFeatures"
offset = 0xa
type = "unsigned char"
size = 0x1

[members.0xb]
name = "PrcbPad12e"
offset = 0xb
type = "unsigned char[1]"
size = 0x1

[members.0xc]
name = "BpbCurrentSpecCtrl"
offset = 0xc
type = "unsigned short"
size = 0x2

[members.0xe]
name = "BpbKernelSpecCtrl"
offset = 0xe
type = "unsigned short"
size = 0x2

[members.0x10]
name = "BpbNmiSpecCtrl"
offset = 0x10
type = "unsigned short"
size = 0x2

[members.0x12]
name = "BpbUserSpecCtrl"
offset = 0x12
type = "unsigned short"
size = 0x2

[members.0x14]
name = "PairRegister"
offset = 0x14
type = "volatile short"
size = 0x2

[members.0x16]
name = "PrcbPad12d"
offset = 0x16
type = "unsigned char[2]"
size = 0x2
