last_change = 2024-07-14T14:49:42.446041Z
name = "$765B7FFCC4FB01A5AB0EE4EE9D978908"
size = 0x2

[members.0x0]
name = "CpuStepping"
offset = 0x0
type = "unsigned char"
size = 0x1

[members.0x1]
name = "CpuModel"
offset = 0x1
type = "unsigned char"
size = 0x1
