last_change = 2024-07-14T14:49:42.461633Z
name = "$888B7D2A033403A4DF437269584615CD"
size = 0x8

[members.0x0]
name = "Count"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x1]
name = "Ptr"
offset = 0x1
type = "void *"
size = 0x8
