last_change = 2024-07-14T14:49:42.461633Z
name = "$9D02AA4AC86E49CEAF084B97B97744B1"
size = 0x4

[members.0x0]
name = "AllocateMisses"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x1]
name = "AllocateHits"
offset = 0x1
type = "unsigned int"
size = 0x4
