last_change = 2024-07-14T14:49:42.461633Z
name = "$9E404EE15DEF3EDCBDC9C6CFB42A825E"
size = 0x38

[members.0x0]
name = "GdtBase"
offset = 0x0
type = "_KGDTENTRY64 *"
size = 0x8

[members.0x8]
name = "TssBase"
offset = 0x8
type = "_KTSS64 *"
size = 0x8

[members.0x10]
name = "UserRsp"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "Self"
offset = 0x18
type = "_KPCR *"
size = 0x8

[members.0x20]
name = "CurrentPrcb"
offset = 0x20
type = "_KPRCB *"
size = 0x8

[members.0x28]
name = "LockArray"
offset = 0x28
type = "_KSPIN_LOCK_QUEUE *"
size = 0x8

[members.0x30]
name = "Used_Self"
offset = 0x30
type = "void *"
size = 0x8
