last_change = 2024-07-14T14:49:42.461633Z
name = "_CONTEXT"
size = 0x4d0

[members.0x0]
name = "P1Home"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "P2Home"
offset = 0x8
type = "unsigned long long"
size = 0x8

[members.0x10]
name = "P3Home"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "P4Home"
offset = 0x18
type = "unsigned long long"
size = 0x8

[members.0x20]
name = "P5Home"
offset = 0x20
type = "unsigned long long"
size = 0x8

[members.0x28]
name = "P6Home"
offset = 0x28
type = "unsigned long long"
size = 0x8

[members.0x30]
name = "ContextFlags"
offset = 0x30
type = "unsigned int"
size = 0x4

[members.0x34]
name = "_MxCsr"
offset = 0x34
type = "unsigned int"
size = 0x4

[members.0x38]
name = "SegCs"
offset = 0x38
type = "unsigned short"
size = 0x2

[members.0x3a]
name = "SegDs"
offset = 0x3a
type = "unsigned short"
size = 0x2

[members.0x3c]
name = "SegEs"
offset = 0x3c
type = "unsigned short"
size = 0x2

[members.0x3e]
name = "SegFs"
offset = 0x3e
type = "unsigned short"
size = 0x2

[members.0x40]
name = "SegGs"
offset = 0x40
type = "unsigned short"
size = 0x2

[members.0x42]
name = "SegSs"
offset = 0x42
type = "unsigned short"
size = 0x2

[members.0x44]
name = "EFlags"
offset = 0x44
type = "unsigned int"
size = 0x4

[members.0x48]
name = "Dr0"
offset = 0x48
type = "unsigned long long"
size = 0x8

[members.0x50]
name = "Dr1"
offset = 0x50
type = "unsigned long long"
size = 0x8

[members.0x58]
name = "Dr2"
offset = 0x58
type = "unsigned long long"
size = 0x8

[members.0x60]
name = "Dr3"
offset = 0x60
type = "unsigned long long"
size = 0x8

[members.0x68]
name = "Dr6"
offset = 0x68
type = "unsigned long long"
size = 0x8

[members.0x70]
name = "Dr7"
offset = 0x70
type = "unsigned long long"
size = 0x8

[members.0x78]
name = "_Rax"
offset = 0x78
type = "unsigned long long"
size = 0x8

[members.0x80]
name = "_Rcx"
offset = 0x80
type = "unsigned long long"
size = 0x8

[members.0x88]
name = "_Rdx"
offset = 0x88
type = "unsigned long long"
size = 0x8

[members.0x90]
name = "_Rbx"
offset = 0x90
type = "unsigned long long"
size = 0x8

[members.0x98]
name = "_Rsp"
offset = 0x98
type = "unsigned long long"
size = 0x8

[members.0xa0]
name = "_Rbp"
offset = 0xa0
type = "unsigned long long"
size = 0x8

[members.0xa8]
name = "_Rsi"
offset = 0xa8
type = "unsigned long long"
size = 0x8

[members.0xb0]
name = "_Rdi"
offset = 0xb0
type = "unsigned long long"
size = 0x8

[members.0xb8]
name = "_R8"
offset = 0xb8
type = "unsigned long long"
size = 0x8

[members.0xc0]
name = "_R9"
offset = 0xc0
type = "unsigned long long"
size = 0x8

[members.0xc8]
name = "_R10"
offset = 0xc8
type = "unsigned long long"
size = 0x8

[members.0xd0]
name = "_R11"
offset = 0xd0
type = "unsigned long long"
size = 0x8

[members.0xd8]
name = "_R12"
offset = 0xd8
type = "unsigned long long"
size = 0x8

[members.0xe0]
name = "_R13"
offset = 0xe0
type = "unsigned long long"
size = 0x8

[members.0xe8]
name = "_R14"
offset = 0xe8
type = "unsigned long long"
size = 0x8

[members.0xf0]
name = "_R15"
offset = 0xf0
type = "unsigned long long"
size = 0x8

[members.0xf8]
name = "_Rip"
offset = 0xf8
type = "unsigned long long"
size = 0x8

[members.0x100]
name = "___u38"
offset = 0x100
type = "$B3C189E9407AF9BCFE54499898634E49"
size = 0x200

[members.0x300]
name = "VectorRegister"
offset = 0x300
type = "_M128A[26]"
size = 0x1a0

[members.0x4a0]
name = "VectorControl"
offset = 0x4a0
type = "unsigned long long"
size = 0x8

[members.0x4a8]
name = "DebugControl"
offset = 0x4a8
type = "unsigned long long"
size = 0x8

[members.0x4b0]
name = "LastBranchToRip"
offset = 0x4b0
type = "unsigned long long"
size = 0x8

[members.0x4b8]
name = "LastBranchFromRip"
offset = 0x4b8
type = "unsigned long long"
size = 0x8

[members.0x4c0]
name = "LastExceptionToRip"
offset = 0x4c0
type = "unsigned long long"
size = 0x8

[members.0x4c8]
name = "LastExceptionFromRip"
offset = 0x4c8
type = "unsigned long long"
size = 0x8
