last_change = 2024-07-14T14:49:42.477285Z
name = "_FILESYSTEM_DISK_COUNTERS"
size = 0x10

[members.0x0]
name = "FsBytesRead"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "FsBytesWritten"
offset = 0x8
type = "unsigned long long"
size = 0x8
