last_change = 2024-07-14T14:49:42.477285Z
name = "_IO_STATUS_BLOCK"
size = 0x10

[members.0x0]
name = "___u0"
offset = 0x0
type = "$250F5FE22B4503EFD7D48C86CC7F2167"
size = 0x8

[members.0x8]
name = "Information"
offset = 0x8
type = "unsigned long long"
size = 0x8
