last_change = 2024-07-14T14:49:42.477285Z
name = "_IO_DRIVER_CREATE_CONTEXT"
size = 0x28

[members.0x0]
name = "Size"
offset = 0x0
type = "short"
size = 0x2

[members.0x8]
name = "ExtraCreateParameter"
offset = 0x8
type = "_ECP_LIST *"
size = 0x8

[members.0x10]
name = "DeviceObjectHint"
offset = 0x10
type = "void *"
size = 0x8

[members.0x18]
name = "TxnParameters"
offset = 0x18
type = "_TXN_PARAMETER_BLOCK *"
size = 0x8

[members.0x20]
name = "SiloContext"
offset = 0x20
type = "_EJOB *"
size = 0x8
