last_change = 2024-07-14T14:49:42.477285Z
name = "_KCLOCK_TICK_TRACE"
size = 0x28

[members.0x0]
name = "PerformanceCounter"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "PreInterruptTime"
offset = 0x8
type = "unsigned long long"
size = 0x8

[members.0x10]
name = "PostInterruptTime"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "TimeStampCounter"
offset = 0x18
type = "unsigned long long"
size = 0x8

[members.0x20]
name = "IsClockOwner"
offset = 0x20
type = "unsigned char"
size = 0x1
