last_change = 2024-07-14T14:49:42.477285Z
name = "_KCLOCK_INCREMENT_TRACE"
size = 0x20

[members.0x0]
name = "ActualIncrement"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "RequestedIncrement"
offset = 0x4
type = "unsigned int"
size = 0x4

[members.0x8]
name = "InterruptTime"
offset = 0x8
type = "unsigned long long"
size = 0x8

[members.0x10]
name = "PerformanceCounter"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "OneShot"
offset = 0x18
type = "unsigned char"
size = 0x1
