last_change = 2024-07-14T14:49:42.477285Z
name = "_KCLOCK_TIMER_STATE"
size = 0x518

[members.0x0]
name = "NextTickDueTime"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "TimeIncrement"
offset = 0x8
type = "unsigned int"
size = 0x4

[members.0xc]
name = "LastRequestedTimeIncrement"
offset = 0xc
type = "unsigned int"
size = 0x4

[members.0x10]
name = "OneShotState"
offset = 0x10
type = "_KCLOCK_TIMER_ONE_SHOT_STATE"
size = 0x4

[members.0x14]
name = "ExpectedWakeReason"
offset = 0x14
type = "_KCLOCK_TIMER_DEADLINE_TYPE"
size = 0x4

[members.0x18]
name = "ClockTimerEntries"
offset = 0x18
type = "_KCLOCK_TIMER_DEADLINE_ENTRY[7]"
size = 0x70

[members.0x88]
name = "ClockActive"
offset = 0x88
type = "unsigned char"
size = 0x1

[members.0x8c]
name = "ClockTickTraceIndex"
offset = 0x8c
type = "unsigned int"
size = 0x4

[members.0x90]
name = "ClockIncrementTraceIndex"
offset = 0x90
type = "unsigned int"
size = 0x4

[members.0x98]
name = "ClockTickTraces"
offset = 0x98
type = "_KCLOCK_TICK_TRACE[16]"
size = 0x280

[members.0x318]
name = "ClockIncrementTraces"
offset = 0x318
type = "_KCLOCK_INCREMENT_TRACE[16]"
size = 0x200
