last_change = 2024-07-14T14:49:42.477285Z
name = "_KDPC"
size = 0x40

[members.0x0]
name = "___u0"
offset = 0x0
type = "$C11F024F64BD56052A3B1C939D857BCE"
size = 0x4

[members.0x8]
name = "DpcListEntry"
offset = 0x8
type = "_SINGLE_LIST_ENTRY"
size = 0x8

[members.0x10]
name = "ProcessorHistory"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "DeferredRoutine"
offset = 0x18
type = "void (__fastcall *)(_KDPC *, void *, void *, void *)"
size = 0x8

[members.0x20]
name = "DeferredContext"
offset = 0x20
type = "void *"
size = 0x8

[members.0x28]
name = "SystemArgument1"
offset = 0x28
type = "void *"
size = 0x8

[members.0x30]
name = "SystemArgument2"
offset = 0x30
type = "void *"
size = 0x8

[members.0x38]
name = "DpcData"
offset = 0x38
type = "void *"
size = 0x8
