last_change = 2024-07-14T14:49:42.477285Z
name = "_KDPC_DATA"
size = 0x30

[members.0x0]
name = "DpcList"
offset = 0x0
type = "_KDPC_LIST"
size = 0x10

[members.0x10]
name = "DpcLock"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "DpcQueueDepth"
offset = 0x18
type = "volatile int"
size = 0x4

[members.0x1c]
name = "DpcCount"
offset = 0x1c
type = "unsigned int"
size = 0x4

[members.0x20]
name = "ActiveDpc"
offset = 0x20
type = "_KDPC *volatile"
size = 0x8

[members.0x28]
name = "LongDpcPresent"
offset = 0x28
type = "unsigned int"
size = 0x4

[members.0x2c]
name = "Padding"
offset = 0x2c
type = "unsigned int"
size = 0x4
