last_change = 2024-07-14T14:49:42.477285Z
name = "_KENTROPY_TIMING_STATE"
size = 0x158

[members.0x0]
name = "EntropyCount"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "Buffer"
offset = 0x4
type = "unsigned int[64]"
size = 0x100

[members.0x108]
name = "Dpc"
offset = 0x108
type = "_KDPC"
size = 0x40

[members.0x148]
name = "LastDeliveredBuffer"
offset = 0x148
type = "unsigned int"
size = 0x4

[members.0x150]
name = "ReservedRawDataBuffer"
offset = 0x150
type = "void *"
size = 0x8
