last_change = 2024-07-14T14:49:42.493044Z
name = "_KSECURE_FAULT_INFORMATION"
size = 0x18

[members.0x0]
name = "FaultCode"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "FaultVa"
offset = 0x8
type = "unsigned long long"
size = 0x8

[members.0x10]
name = "FaultPa"
offset = 0x10
type = "unsigned long long"
size = 0x8
