last_change = 2024-07-14T14:49:42.493044Z
name = "_KSPECIAL_REGISTERS"
size = 0xf0

[members.0x0]
name = "Cr0"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "Cr2"
offset = 0x8
type = "unsigned long long"
size = 0x8

[members.0x10]
name = "Cr3"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "Cr4"
offset = 0x18
type = "unsigned long long"
size = 0x8

[members.0x20]
name = "KernelDr0"
offset = 0x20
type = "unsigned long long"
size = 0x8

[members.0x28]
name = "KernelDr1"
offset = 0x28
type = "unsigned long long"
size = 0x8

[members.0x30]
name = "KernelDr2"
offset = 0x30
type = "unsigned long long"
size = 0x8

[members.0x38]
name = "KernelDr3"
offset = 0x38
type = "unsigned long long"
size = 0x8

[members.0x40]
name = "KernelDr6"
offset = 0x40
type = "unsigned long long"
size = 0x8

[members.0x48]
name = "KernelDr7"
offset = 0x48
type = "unsigned long long"
size = 0x8

[members.0x50]
name = "Gdtr"
offset = 0x50
type = "_KDESCRIPTOR"
size = 0x10

[members.0x60]
name = "Idtr"
offset = 0x60
type = "_KDESCRIPTOR"
size = 0x10

[members.0x70]
name = "Tr"
offset = 0x70
type = "unsigned short"
size = 0x2

[members.0x72]
name = "Ldtr"
offset = 0x72
type = "unsigned short"
size = 0x2

[members.0x74]
name = "_MxCsr"
offset = 0x74
type = "unsigned int"
size = 0x4

[members.0x78]
name = "DebugControl"
offset = 0x78
type = "unsigned long long"
size = 0x8

[members.0x80]
name = "LastBranchToRip"
offset = 0x80
type = "unsigned long long"
size = 0x8

[members.0x88]
name = "LastBranchFromRip"
offset = 0x88
type = "unsigned long long"
size = 0x8

[members.0x90]
name = "LastExceptionToRip"
offset = 0x90
type = "unsigned long long"
size = 0x8

[members.0x98]
name = "LastExceptionFromRip"
offset = 0x98
type = "unsigned long long"
size = 0x8

[members.0xa0]
name = "Cr8"
offset = 0xa0
type = "unsigned long long"
size = 0x8

[members.0xa8]
name = "MsrGsBase"
offset = 0xa8
type = "unsigned long long"
size = 0x8

[members.0xb0]
name = "MsrGsSwap"
offset = 0xb0
type = "unsigned long long"
size = 0x8

[members.0xb8]
name = "MsrStar"
offset = 0xb8
type = "unsigned long long"
size = 0x8

[members.0xc0]
name = "MsrLStar"
offset = 0xc0
type = "unsigned long long"
size = 0x8

[members.0xc8]
name = "MsrCStar"
offset = 0xc8
type = "unsigned long long"
size = 0x8

[members.0xd0]
name = "MsrSyscallMask"
offset = 0xd0
type = "unsigned long long"
size = 0x8

[members.0xd8]
name = "Xcr0"
offset = 0xd8
type = "unsigned long long"
size = 0x8

[members.0xe0]
name = "MsrFsBase"
offset = 0xe0
type = "unsigned long long"
size = 0x8

[members.0xe8]
name = "SpecialPadding0"
offset = 0xe8
type = "unsigned long long"
size = 0x8
