last_change = 2024-07-14T14:49:42.493044Z
name = "_KTIMER_TABLE_ENTRY"
size = 0x20

[members.0x0]
name = "Lock"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "Entry"
offset = 0x8
type = "_LIST_ENTRY"
size = 0x10

[members.0x18]
name = "Time"
offset = 0x18
type = "_ULARGE_INTEGER"
size = 0x8
