last_change = 2024-07-14T14:49:42.493044Z
name = "_KTIMER_EXPIRATION_TRACE"
size = 0x10

[members.0x0]
name = "InterruptTime"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "PerformanceCounter"
offset = 0x8
type = "_LARGE_INTEGER"
size = 0x8
