last_change = 2024-07-14T14:49:42.493044Z
name = "_LARGE_INTEGER::$824E624842C29B0A9DF85A636208834D"
size = 0x8

[members.0x0]
name = "LowPart"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "HighPart"
offset = 0x4
type = "LONG"
size = 0x4
