last_change = 2024-07-14T14:49:42.493044Z
name = "_M128A"
size = 0x10

[members.0x0]
name = "Low"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "High"
offset = 0x8
type = "long long"
size = 0x8
