last_change = 2024-07-14T14:49:42.493044Z
name = "_MACHINE_CHECK_CONTEXT"
size = 0x50

[members.0x0]
name = "MachineFrame"
offset = 0x0
type = "_MACHINE_FRAME"
size = 0x28

[members.0x28]
name = "_Rax"
offset = 0x28
type = "unsigned long long"
size = 0x8

[members.0x30]
name = "_Rcx"
offset = 0x30
type = "unsigned long long"
size = 0x8

[members.0x38]
name = "_Rdx"
offset = 0x38
type = "unsigned long long"
size = 0x8

[members.0x40]
name = "GsBase"
offset = 0x40
type = "unsigned long long"
size = 0x8

[members.0x48]
name = "Cr3"
offset = 0x48
type = "unsigned long long"
size = 0x8
