last_change = 2024-07-14T14:49:42.493044Z
name = "_MM_STORE_KEY"
size = 0x8

[members.0x0]
name = "__s0"
offset = 0x0
type = "$53CE3244FE3C33F765C2E9729EA486BE"
size = 0x8

[members.0x1]
name = "EntireKey"
offset = 0x1
type = "unsigned long long"
size = 0x8
