last_change = 2024-07-14T14:49:42.493044Z
name = "_OBJECT_HANDLE_INFORMATION"
size = 0x8

[members.0x0]
name = "HandleAttributes"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "GrantedAccess"
offset = 0x4
type = "unsigned int"
size = 0x4
