last_change = 2024-07-14T14:49:42.493044Z
name = "_OSVERSIONINFOW"
size = 0x114

[members.0x0]
name = "dwOSVersionInfoSize"
offset = 0x0
type = "ULONG"
size = 0x4

[members.0x4]
name = "dwMajorVersion"
offset = 0x4
type = "ULONG"
size = 0x4

[members.0x8]
name = "dwMinorVersion"
offset = 0x8
type = "ULONG"
size = 0x4

[members.0xc]
name = "dwBuildNumber"
offset = 0xc
type = "ULONG"
size = 0x4

[members.0x10]
name = "dwPlatformId"
offset = 0x10
type = "ULONG"
size = 0x4

[members.0x14]
name = "szCSDVersion"
offset = 0x14
type = "WCHAR[128]"
size = 0x100
