last_change = 2024-07-14T14:49:42.493044Z
name = "_PPM_IDLE_SYNCHRONIZATION_STATE"
size = 0x4

[members.0x0]
name = "AsLong"
offset = 0x0
type = "int"
size = 0x4

[members.0x1]
name = "__s1"
offset = 0x1
type = "$4C54FEED1D206CF6DD53948246B9325F"
size = 0x4
