last_change = 2024-07-14T14:49:42.493044Z
name = "_PPM_FFH_THROTTLE_STATE_INFO"
size = 0x20

[members.0x0]
name = "EnableLogging"
offset = 0x0
type = "unsigned char"
size = 0x1

[members.0x4]
name = "MismatchCount"
offset = 0x4
type = "unsigned int"
size = 0x4

[members.0x8]
name = "Initialized"
offset = 0x8
type = "unsigned char"
size = 0x1

[members.0x10]
name = "LastValue"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "LastLogTickCount"
offset = 0x18
type = "_LARGE_INTEGER"
size = 0x8
