last_change = 2024-07-14T14:49:42.493044Z
name = "_PROCESSOR_POWER_STATE"
size = 0x238

[members.0x0]
name = "IdleStates"
offset = 0x0
type = "_PPM_IDLE_STATES *"
size = 0x8

[members.0x8]
name = "IdleAccounting"
offset = 0x8
type = "_PROC_IDLE_ACCOUNTING *"
size = 0x8

[members.0x10]
name = "IdleTimeLast"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "IdleTimeTotal"
offset = 0x18
type = "unsigned long long"
size = 0x8

[members.0x20]
name = "IdleSequenceNumber"
offset = 0x20
type = "volatile unsigned long long"
size = 0x8

[members.0x28]
name = "IdleTimeEntry"
offset = 0x28
type = "unsigned long long"
size = 0x8

[members.0x30]
name = "___u6"
offset = 0x30
type = "$1C522E00CDFB3DDA2387AB30959AD8DB"
size = 0x8

[members.0x38]
name = "NonInterruptibleTransition"
offset = 0x38
type = "unsigned char"
size = 0x1

[members.0x39]
name = "PepWokenTransition"
offset = 0x39
type = "unsigned char"
size = 0x1

[members.0x3a]
name = "HvTargetState"
offset = 0x3a
type = "unsigned char"
size = 0x1

[members.0x3b]
name = "SoftParked"
offset = 0x3b
type = "unsigned char"
size = 0x1

[members.0x3c]
name = "TargetIdleState"
offset = 0x3c
type = "unsigned int"
size = 0x4

[members.0x40]
name = "IdlePolicy"
offset = 0x40
type = "_PROC_IDLE_POLICY"
size = 0x6

[members.0x48]
name = "Synchronization"
offset = 0x48
type = "volatile _PPM_IDLE_SYNCHRONIZATION_STATE"
size = 0x4

[members.0x50]
name = "PerfFeedback"
offset = 0x50
type = "_PROC_FEEDBACK"
size = 0x90

[members.0xe0]
name = "Hypervisor"
offset = 0xe0
type = "_PROC_HYPERVISOR_STATE"
size = 0x4

[members.0xe4]
name = "LastSysTime"
offset = 0xe4
type = "unsigned int"
size = 0x4

[members.0xe8]
name = "WmiDispatchPtr"
offset = 0xe8
type = "unsigned long long"
size = 0x8

[members.0xf0]
name = "WmiInterfaceEnabled"
offset = 0xf0
type = "int"
size = 0x4

[members.0xf8]
name = "FFHThrottleStateInfo"
offset = 0xf8
type = "_PPM_FFH_THROTTLE_STATE_INFO"
size = 0x20

[members.0x118]
name = "PerfActionDpc"
offset = 0x118
type = "_KDPC"
size = 0x40

[members.0x158]
name = "PerfActionMask"
offset = 0x158
type = "volatile int"
size = 0x4

[members.0x160]
name = "HvIdleCheck"
offset = 0x160
type = "_PROC_IDLE_SNAP"
size = 0x10

[members.0x170]
name = "CheckContext"
offset = 0x170
type = "_PROC_PERF_CHECK_CONTEXT"
size = 0x48

[members.0x1b8]
name = "Concurrency"
offset = 0x1b8
type = "_PPM_CONCURRENCY_ACCOUNTING *"
size = 0x8

[members.0x1c0]
name = "ClassConcurrency"
offset = 0x1c0
type = "_PPM_CONCURRENCY_ACCOUNTING *"
size = 0x8

[members.0x1c8]
name = "ArchitecturalEfficiencyClass"
offset = 0x1c8
type = "unsigned char"
size = 0x1

[members.0x1c9]
name = "PerformanceSchedulingClass"
offset = 0x1c9
type = "unsigned char"
size = 0x1

[members.0x1ca]
name = "EfficiencySchedulingClass"
offset = 0x1ca
type = "unsigned char"
size = 0x1

[members.0x1cb]
name = "EarlyBootArchitecturalEfficiencyClass"
offset = 0x1cb
type = "unsigned char"
size = 0x1

[members.0x1cc]
name = "Parked"
offset = 0x1cc
type = "unsigned char"
size = 0x1

[members.0x1cd]
name = "LongPriorQosPeriod"
offset = 0x1cd
type = "unsigned char"
size = 0x1

[members.0x1d0]
name = "___u32"
offset = 0x1d0
type = "$1295C7652040702D9335A0311A3EC089"
size = 0x8

[members.0x1d8]
name = "ActiveTime"
offset = 0x1d8
type = "unsigned long long"
size = 0x8

[members.0x1e0]
name = "TotalTime"
offset = 0x1e0
type = "unsigned long long"
size = 0x8

[members.0x1e8]
name = "FxDevice"
offset = 0x1e8
type = "_POP_FX_DEVICE *"
size = 0x8

[members.0x1f0]
name = "LastQosTranstionTsc"
offset = 0x1f0
type = "unsigned long long"
size = 0x8

[members.0x1f8]
name = "QosTransitionHysteresis"
offset = 0x1f8
type = "unsigned long long"
size = 0x8

[members.0x200]
name = "RequestedQosClass"
offset = 0x200
type = "_KHETERO_CPU_QOS"
size = 0x4

[members.0x204]
name = "ResolvedQosClass"
offset = 0x204
type = "_KHETERO_CPU_QOS"
size = 0x4

[members.0x208]
name = "QosEquivalencyMask"
offset = 0x208
type = "unsigned short"
size = 0x2

[members.0x20a]
name = "HwFeedbackTableOffset"
offset = 0x20a
type = "unsigned short"
size = 0x2

[members.0x20c]
name = "HwFeedbackParkHint"
offset = 0x20c
type = "unsigned char"
size = 0x1

[members.0x20d]
name = "HeteroCoreType"
offset = 0x20d
type = "unsigned char"
size = 0x1

[members.0x20e]
name = "HwFeedbackTableIndex"
offset = 0x20e
type = "unsigned short"
size = 0x2

[members.0x210]
name = "HwFeedbackClassList"
offset = 0x210
type = "_KHETRO_HWFEEDBACK_TYPE *"
size = 0x8

[members.0x218]
name = "EeCyclesWorkloadClassList"
offset = 0x218
type = "_PROCESSOR_CYCLES_WORKLOAD_CLASS *"
size = 0x8

[members.0x220]
name = "PerfCyclesWorkloadClassList"
offset = 0x220
type = "_PROCESSOR_CYCLES_WORKLOAD_CLASS *"
size = 0x8

[members.0x228]
name = "NotUsed"
offset = 0x228
type = "unsigned char"
size = 0x1

[members.0x22a]
name = "FrequencyBucketThresholds"
offset = 0x22a
type = "unsigned short[4]"
size = 0x8
