last_change = 2024-07-14T14:49:42.493044Z
name = "_PROCESSOR_NUMBER"
size = 0x4

[members.0x0]
name = "Group"
offset = 0x0
type = "unsigned short"
size = 0x2

[members.0x2]
name = "Number"
offset = 0x2
type = "unsigned char"
size = 0x1

[members.0x3]
name = "Reserved"
offset = 0x3
type = "unsigned char"
size = 0x1
