last_change = 2024-07-14T14:49:42.493044Z
name = "_PROC_FEEDBACK"
size = 0x90

[members.0x0]
name = "Lock"
offset = 0x0
type = "unsigned long long"
size = 0x8

[members.0x8]
name = "CyclesLast"
offset = 0x8
type = "unsigned long long"
size = 0x8

[members.0x10]
name = "CyclesActive"
offset = 0x10
type = "unsigned long long"
size = 0x8

[members.0x18]
name = "Counters"
offset = 0x18
type = "_PROC_FEEDBACK_COUNTER *[2]"
size = 0x10

[members.0x28]
name = "LastUpdateTime"
offset = 0x28
type = "unsigned long long"
size = 0x8

[members.0x30]
name = "UnscaledTime"
offset = 0x30
type = "unsigned long long"
size = 0x8

[members.0x38]
name = "UnaccountedTime"
offset = 0x38
type = "volatile long long"
size = 0x8

[members.0x40]
name = "ScaledTime"
offset = 0x40
type = "unsigned long long[2]"
size = 0x10

[members.0x50]
name = "UnaccountedKernelTime"
offset = 0x50
type = "unsigned long long"
size = 0x8

[members.0x58]
name = "PerformanceScaledKernelTime"
offset = 0x58
type = "unsigned long long"
size = 0x8

[members.0x60]
name = "UserTimeLast"
offset = 0x60
type = "unsigned int"
size = 0x4

[members.0x64]
name = "KernelTimeLast"
offset = 0x64
type = "unsigned int"
size = 0x4

[members.0x68]
name = "IdleGenerationNumberLast"
offset = 0x68
type = "unsigned long long"
size = 0x8

[members.0x70]
name = "HvActiveTimeLast"
offset = 0x70
type = "unsigned long long"
size = 0x8

[members.0x78]
name = "StallCyclesLast"
offset = 0x78
type = "unsigned long long"
size = 0x8

[members.0x80]
name = "StallTime"
offset = 0x80
type = "unsigned long long"
size = 0x8

[members.0x88]
name = "KernelTimesIndex"
offset = 0x88
type = "unsigned char"
size = 0x1

[members.0x89]
name = "CounterDiscardsIdleTime"
offset = 0x89
type = "unsigned char"
size = 0x1

[members.0x8a]
name = "CounterReadOptimize"
offset = 0x8a
type = "unsigned char"
size = 0x1
