last_change = 2024-07-14T14:49:42.493044Z
name = "_RTL_DYNAMIC_HASH_TABLE_ENTRY"
size = 0x18

[members.0x0]
name = "Linkage"
offset = 0x0
type = "_LIST_ENTRY"
size = 0x10

[members.0x10]
name = "Signature"
offset = 0x10
type = "unsigned long long"
size = 0x8
