last_change = 2024-07-14T14:49:42.493044Z
name = "_SID_AND_ATTRIBUTES"
size = 0x10

[members.0x0]
name = "Sid"
offset = 0x0
type = "void *"
size = 0x8

[members.0x8]
name = "Attributes"
offset = 0x8
type = "unsigned int"
size = 0x4
