last_change = 2024-07-14T14:49:42.493044Z
name = "_TOKEN_PRIVILEGES"
size = 0x10

[members.0x0]
name = "PrivilegeCount"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x4]
name = "Privileges"
offset = 0x4
type = "_LUID_AND_ATTRIBUTES[1]"
size = 0xc
