last_change = 2024-07-14T14:49:42.461633Z
name = "CLFS_WRITE_ENTRY"
size = 0x10

[members.0x0]
name = "Buffer"
offset = 0x0
type = "PVOID"
size = 0x8

[members.0x8]
name = "ByteLength"
offset = 0x8
type = "ULONG"
size = 0x4
