last_change = 2024-07-14T14:49:42.461633Z
name = "EVENT_DESCRIPTOR"
size = 0x10

[members.0x0]
name = "Id"
offset = 0x0
type = "unsigned short"
size = 0x2

[members.0x2]
name = "Version"
offset = 0x2
type = "unsigned char"
size = 0x1

[members.0x3]
name = "Channel"
offset = 0x3
type = "unsigned char"
size = 0x1

[members.0x4]
name = "Level"
offset = 0x4
type = "unsigned char"
size = 0x1

[members.0x5]
name = "Opcode"
offset = 0x5
type = "unsigned char"
size = 0x1

[members.0x6]
name = "Task"
offset = 0x6
type = "unsigned short"
size = 0x2

[members.0x8]
name = "Keyword"
offset = 0x8
type = "unsigned long long"
size = 0x8
