last_change = 2024-07-14T14:49:42.461633Z
name = "RTL_BITMAP"
size = 0x10

[members.0x0]
name = "SizeOfBitMap"
offset = 0x0
type = "unsigned int"
size = 0x4

[members.0x8]
name = "Buffer"
offset = 0x8
type = "unsigned int *"
size = 0x8
